<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name ="description" content="This is the provider side for the final Cafe Quest Version">
        <title>User Dashboard</title>
        <link rel="stylesheet" href="/css/user_dashboard.css">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous"> 
        <script src="https://kit.fontawesome.com/e346597b68.js" crossorigin="anonymous"></script>
        <title>Provider-Side Dashboard of Active Users</title>
    </head>
    <body style="background-color: #f4efe7"> 
        <div class="topbar">
            <img class="logo" src="/img/cafequest_logo.png" alt="cafequest_logo">
        </div>
        <div class="dashboard">


            
        </div>
    </body>
</html>